#!/usr/bin/env bun

/**
 * Example 05: Security Configuration
 *
 * This example demonstrates Shotput's security features for controlling
 * what resources can be accessed during template processing.
 *
 * Security Features:
 *   - Path validation and restrictions
 *   - Allowed base paths
 *   - HTTP domain whitelisting
 *   - Function execution controls
 *   - Skills source restrictions
 *
 * Usage:
 *   bun run examples/advanced/05-security.ts
 */

import { shotput } from "../../src/index";
import { writeFileSync, mkdirSync } from "fs";
import { join } from "path";
import { getLogger } from "../../src/logger";

const log = getLogger("05-security");
const templateDir = join(import.meta.dir, "../output/05-security");
const dataDir = join(import.meta.dir, "../data");
mkdirSync(templateDir, { recursive: true });

const safeTemplate = `# Secure File Access

## Allowed: Files in data directory
{{../../data/config.json}}

## This would fail: Accessing system files
{{/etc/passwd}}

## This would fail: Path traversal attempt
{{../../../.ssh/id_rsa}}
`;

const safeTemplatePath = join(templateDir, "safe-template.md");
writeFileSync(safeTemplatePath, safeTemplate);

try {
  const result = await shotput({
    templateDir,
    templateFile: "safe-template.md",
    responseDir: templateDir,
    // Only allow access to the data directory
    allowedBasePaths: [dataDir],
    debug: true,
    debugFile: join(templateDir, "safe-debug.md"),
  });

  log.info(result.content);
} catch (error) {
  log.error(error);
}

const httpTemplate = `# HTTP Access Control

## Allowed domain
{{https://api.github.com/zen}}

## This would fail: Blocked domain
{{https://evil-site.com/data}}

## This would fail: HTTP disabled
{{http://example.com/data}}
`;

const httpTemplatePath = join(templateDir, "http-template.md");
writeFileSync(httpTemplatePath, httpTemplate);

try {
  const result = await shotput({
    templateDir,
    templateFile: "http-template.md",
    responseDir: templateDir,
    allowHttp: true,
    // Only allow specific domains
    allowedDomains: ["api.github.com", "api.example.com"],
    httpTimeout: 5000,
    debug: true,
    debugFile: join(templateDir, "http-debug.md"),
  });

  log.info(result.content);
} catch (error) {
  log.error("HTTP validation failed:", error);
}

// Create a sample function
const functionContent = `
export default async function(result, path, match, remainingLength) {
  const content = "Generated by secure function";
  return {
    operationResults: result.replace(match, content),
    combinedRemainingCount: remainingLength - content.length,
  };
}
`;

const functionPath = join(dataDir, "secure-function.js");
writeFileSync(functionPath, functionContent);

const functionTemplate = `# Function Security

## Allowed function
{{TemplateType.Function:../../data/secure-function.js}}

## This would fail: Function in unauthorized location
{{TemplateType.Function:/tmp/unsafe.js}}
`;

const functionTemplatePath = join(templateDir, "function-template.md");
writeFileSync(functionTemplatePath, functionTemplate);

try {
  const result = await shotput({
    templateDir,
    templateFile: "function-template.md",
    responseDir: templateDir,
    allowFunctions: true,
    // Only allow functions from data directory
    allowedFunctionPaths: [dataDir],
    allowedBasePaths: [dataDir, templateDir],
    debug: true,
    debugFile: join(templateDir, "function-debug.md"),
  });

  log.info(result.content);
} catch (error) {
  log.error("Function validation failed:", error);
}

const skillsTemplate = `# Skills Security

## Local skill (always allowed if skillsDir is accessible)
{{skill:local-skill}}

## Remote skill from allowed source
{{skill:github:anthropics/skills/brand-guidelines}}

## This would fail: Unauthorized remote source
{{skill:github:untrusted-org/malicious-skills/bad-skill}}
`;

const skillsTemplatePath = join(templateDir, "skills-template.md");
writeFileSync(skillsTemplatePath, skillsTemplate);

try {
  const { content } = await shotput({
    templateDir,
    templateFile: "skills-template.md",
    responseDir: templateDir,
    skillsDir: join(import.meta.dir, "../skills"),
    allowRemoteSkills: true,
    // Only allow skills from trusted organizations
    allowedSkillSources: ["anthropics/skills", "myorg/skills"],
    allowedBasePaths: [dataDir, templateDir, join(import.meta.dir, "..")],
    debug: true,
    debugFile: join(templateDir, "skills-debug.md"),
  });

  log.info(content);
} catch (error) {
  log.error("Skills validation:", error);
}

// Example 5: Complete Secure Configuration
log.info("\n=== Example 5: Complete Secure Configuration ===");

const secureConfig = {
  templateDir,
  templateFile: "safe-template.md",
  responseDir: templateDir,

  // File access restrictions
  allowedBasePaths: [dataDir, templateDir],

  // HTTP restrictions
  allowHttp: true,
  allowedDomains: ["api.github.com"],
  httpTimeout: 10000,

  // Function restrictions
  allowFunctions: true,
  allowedFunctionPaths: [dataDir],

  // Skills restrictions
  skillsDir: join(import.meta.dir, "../skills"),
  allowRemoteSkills: false, // Disable remote skills for maximum security

  // Length limits
  maxPromptLength: 100000,
  maxBucketFiles: 50,

  // S3 (if needed)
  s3AccessKeyId: process.env["S3_ACCESS_KEY_ID"],
  s3SecretAccessKey: process.env["S3_SECRET_ACCESS_KEY"],
  s3Region: process.env["S3_REGION"],

  debug: false, // Disable debug output in production
};

log.info("Secure configuration example:");
log.info(`  File access: ${secureConfig.allowedBasePaths.length} allowed paths`);
log.info(`  HTTP: ${secureConfig.allowHttp ? 'enabled' : 'disabled'} (${secureConfig.allowedDomains?.length || 0} allowed domains)`);
log.info(`  Functions: ${secureConfig.allowFunctions ? 'enabled' : 'disabled'}`);
log.info(`  Remote skills: ${secureConfig.allowRemoteSkills ? 'enabled' : 'disabled'}`);
log.info(`  Max output: ${secureConfig.maxPromptLength} characters`);

/**
 * Key Takeaways:
 *
 * 1. Always set allowedBasePaths to restrict file access
 * 2. Use allowedDomains to whitelist HTTP endpoints
 * 3. Disable allowFunctions unless absolutely needed
 * 4. Set allowRemoteSkills: false in production
 * 5. Use allowedSkillSources to whitelist remote skill sources
 * 6. Set maxPromptLength to prevent resource exhaustion
 * 7. Disable debug mode in production
 * 8. Path traversal attempts are automatically blocked
 * 9. All security violations are reported in metadata.errors
 * 10. Principle of least privilege: only enable what you need
 */
