#!/usr/bin/env bun

/**
 * Example 07: Custom Functions
 *
 * This example demonstrates using custom JavaScript functions in templates.
 * Functions allow you to:
 * - Generate dynamic content
 * - Process and transform data
 * - Call external APIs or databases
 * - Perform complex logic
 *
 * Usage:
 *   bun run examples/basic/07-functions.ts
 */

import { shotput } from "../../src/index";
import { writeFileSync, mkdirSync } from "fs";
import { join } from "path";
import { getLogger } from "../../src/logger";

const log = getLogger("07-functions");
const templateDir = join(import.meta.dir, "../output/07-functions");
mkdirSync(templateDir, { recursive: true });
const templateContent = `# Custom Function Examples

## Example 1: Transform Function

This function generates dynamic content with timestamps:

{{TemplateType.Function:../../functions/transform.js}}

## Example 2: Data Processor Function

This function processes and formats data:

{{TemplateType.Function:../../functions/data-processor.js}}

## Static Content

Functions can be mixed with static content and other template types.
Here's a regular file inclusion:

{{../../data/config.json}}

---

Functions provide powerful extensibility for template processing!
`;

const templatePath = join(templateDir, "template.md");
writeFileSync(templatePath, templateContent);

try {
  const result = await shotput({
    templateDir,
    templateFile: "template.md",
    responseDir: templateDir,
    allowedBasePaths: [join(import.meta.dir, "..")],
    allowFunctions: true, // IMPORTANT: Must enable function execution
    allowedFunctionPaths: [join(import.meta.dir, "../functions")], // Restrict function paths
    debug: true,
    debugFile: join(templateDir, "template-debug.md"),
  });

  log.info(result);

  // Create a simple inline function
  const inlineFunctionPath = join(templateDir, "inline-function.js");
  const inlineFunctionContent = `
export default async function(result, path, match, remainingLength) {
  const content = \`
## Inline Function Output

Current timestamp: \${Date.now()}
Template path: \${path}
Match string: \${match}

This content was generated by an inline function!
\`;

  return {
    operationResults: result.replace(match, content),
    combinedRemainingCount: remainingLength - content.length,
  };
}
`;

  writeFileSync(inlineFunctionPath, inlineFunctionContent);

  const inlineTemplate = `# Inline Function Test

{{TemplateType.Function:./inline-function.js}}

Complete!
`;

  const inlineTemplatePath = join(templateDir, "inline-template.md");
  writeFileSync(inlineTemplatePath, inlineTemplate);

  const inlineResult = await shotput({
    templateDir,
    templateFile: "inline-template.md",
    responseDir: templateDir,
    allowedBasePaths: [join(import.meta.dir, "..")],
    allowFunctions: true,
    allowedFunctionPaths: [templateDir, join(import.meta.dir, "../functions")],
    debug: true,
    debugFile: join(templateDir, "inline-template-debug.md"),
  });

  log.info(inlineResult);
} catch (error) {
  log.error(error);
  log.error("Possible causes:");
  log.error("- allowFunctions is not set to true");
  log.error("- Function path is not in allowedFunctionPaths");
  log.error("- Function syntax error");
  log.error("- Function doesn't export default async function");

}

/**
 * Key Takeaways:
 *
 * 1. Function Syntax:
 *    {{TemplateType.Function:/path/to/function.js}}
 *    - Must use "TemplateType.Function:" prefix
 *    - Path can be absolute or relative
 *
 * 2. Security Configuration:
 *    - MUST set allowFunctions: true
 *    - MUST specify allowedFunctionPaths
 *    - Functions outside allowed paths will be blocked
 *
 * 3. Function Signature:
 *    export default async function(result, path, match, remainingLength) {
 *      const content = "your generated content";
 *      return {
 *        operationResults: result.replace(match, content),
 *        combinedRemainingCount: remainingLength - content.length,
 *      };
 *    }
 *
 * 4. Function Parameters:
 *    - result: Current template content being processed
 *    - path: Path to the function file
 *    - match: The template marker string (e.g., "{{TemplateType.Function:...}}")
 *    - remainingLength: Remaining allowed length for content
 *
 * 5. Return Value:
 *    - operationResults: The result with match replaced by your content
 *    - combinedRemainingCount: Updated remaining length
 *
 * 6. Function Capabilities:
 *    - Generate dynamic content
 *    - Call external APIs
 *    - Read from databases
 *    - Process environment variables
 *    - Transform and format data
 *    - Perform complex calculations
 *    - Read other files (with appropriate permissions)
 *
 * 7. Module Format:
 *    - ES modules (export default) preferred
 *    - CommonJS (module.exports) also supported
 *    - Function must be async
 *
 * 8. Best Practices:
 *    - Keep functions focused and single-purpose
 *    - Handle errors gracefully
 *    - Respect remainingLength limits
 *    - Document function parameters and behavior
 *    - Test functions in isolation
 *    - Use TypeScript for type safety (optional)
 *
 * 9. Common Use Cases:
 *    - Fetching data from APIs
 *    - Generating timestamps and metadata
 *    - Processing and aggregating data
 *    - Formatting complex output
 *    - Environment-specific content
 *    - Conditional content generation
 *
 * 10. Security Considerations:
 *     - Only allow trusted function paths
 *     - Validate function inputs
 *     - Be careful with external API calls
 *     - Limit file system access
 *     - Consider timeout mechanisms for long-running functions
 */
